import {Dimensions} from 'react-native';
import {fontResize} from './fontResize';

const CONSTANTS = {
  TEXT: {
    WELCOME_TO: 'Welcome to Noota!',
    BACK: 'Back',
    VERIFICATION_CODE: 'Enter verification Code',
    VALID_VERIFICATION_CODE: 'Please enter valid verification code',
    PLEASE_ENTER_CODE: 'Please enter the code we sent to',
    RESEND_CODE: 'Resend code',
    DIDNOT_RECEIVE_CODE: 'Didn’t receive a code?',
    OR: 'Or',
    CONTINUE: 'Continue',
    NAME: 'Name',
    ENTER_NAME: 'Enter your name',
    EMAIL_ADDRESS: 'Email Address',
    ENTER_EMAIL_ADDRESS: 'Enter email address',
    ENTER_PASSWORD: 'Enter password',
    CONNECT_CALENDER: 'Connect your calendar',
    CAPTURE_CALENDER:
      'Connect your calendar to capture and generate AI-Summary automatically.',
    CALENDER_POLICY:
      'Your calendar data is stored securely and used only as described in our Privacy Policy.',
    ONE_CLICK_RECORD: 'One click to record them all',
    TO_ENSURE: `To ensure Noota offers you the most relevant and personalized experience, we'd like to know a bit more about you.`,
    SELECT_ROLE: 'Select your role',
    SAVE_DETAILS: 'Save Details',
    AI_WORKFLOWS: 'AI workflows',
    SELECT_AI_WORKFLOWS:
      'Select the workflows that best represent your meetings, can be changed later.',
    ACTIVATE_FREE_TRIAL: 'Activate free trial',
    UPCOMING_MEETING: 'Upcoming meetings',
    ADD_ONLINE_MEETING: 'Add to online meeting',
    OK: 'OK',
    ONLINE: 'Online',
    VERIFY: 'Verify',
    NEXT: 'Next',
    Skip: 'Skip',
    UPDATE: 'Update',
    LOGIN: 'Login',
    FIRST_NAME: 'First Name',
    DOB: 'Date Of Birth',
    OFFLINE: 'offline',
    CHAT: 'Chat',
    REVIEWS: 'REVIEWS',
    SETTING: 'SETTING',
    LOGOUT: 'LOGOUT',
    SETTINGS: 'Settings',
    SERVICES: 'Services',
    RATE_US: 'Rate us',
    CUSTOMER_SUPPORT: 'Customer Support',
    NOW: 'Now',
    CHOOSE_PROFILE_PHOTO: 'Choose Profile Picture',
    CHOOSE_FROM_GALLERY: 'Choose from gallery',
    CHOOSE_FROM_CAMERA: 'Choose from camera',
    CANCEL: 'Cancel',
    CAMERA_PERMISSION: 'Camera Permission',
    PERMISSION_MESSAGE: 'App needs camera permission',
    NEW_USER: ' New user? ',
    LOG_IN: 'Log in',
    FORGOT_PASSWORD: 'Forgot\nPassword',
    I_ALREADY_ACCOUNT: 'I aleady have an account',
    OR_CONTINUE_WITH: 'Or continue with',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    Username: 'Username',
    SIGN_UP: 'Sign up',
    SIGN_IN: 'Sign in',
    FORGOT_YOUR_PASSWORD: 'Forgot your password?',
    ACCEPT: 'Accept',
    REJECT: 'Reject',
    VIEW_ALL: 'View all',
    ALERT_TITLE: 'Alert',
    YES: 'Yes',
    OKAY: 'Okay',
    DELETE: 'Delete',
    NO: 'No',
    SAVE: 'Save',
    NOTIFICATION: 'Notification',
    APPLY: 'Apply',
    TYPE_YOUR_MESSAGE: 'Type your message here',
    LEAVE: 'Leave',
    SUBMIT: 'Submit',
    ADD_MONEY: 'Add money to wallet',
    DELETE_ACCOUNT: 'Delete account',
    SESSION_EXPIRED: 'Session Expired',
    YOU_HAVE_LOGIN:
      'You are already login another system. If you have  using this functionality then please login?',
    LOGIN_WITH_GOOGLE: 'Log in with Google',
    LOGIN_WITH_OUTLOOK: 'Log in with Outlook',
    GOOGLE_CALENDER: 'Google calendar',
    OUTLOOK_CALENDER: 'Outlook calendar',
  },
  PERMISSION_MESSGAE: {
    PERMISSION_NOTITIFCATION_MESSAGE:
      'Please turn on notification permission manually',
    BLOCKED_PERMISSION: 'The permission is denied and not requestable anymore',
    CANNOT_OPEN: 'cannot open settings',
    GRANTED_PERMISSION: 'The permission is granted',
    LIMITED_PERMISSION: 'The permission is limited: some actions are possible',
    DENIED_PERMISSION:
      'The permission has not been requested / is denied but requestable',
    UNIAVAILABLE_PERMISSION:
      'This feature is not available (on this device / in this context)',
    BLOCK_USER_MESSAGE: 'You blocked this account. Tap to unblock',
  },
  STYLE_TYPE: {
    CANCEL: 'cancel',
    SUCCESS: 'success',
    ERROR: 'error',
    PADDING: 'padding',
  },
  ERROR_MESSAGE: {
    YOU_HAVE: 'You have',
    ATTEMPS_LEFT: 'attempts left',
    PASSWORD_EMAIL: 'Your password or email do not match',
    YOU_ARE_BLOCKED:
      'You are currently blocked from the app.Please start the pin recovery procedure.',
  },
  formik_Key: {
    PASSWORD: 'password',
    EMAIL_ADDRESS: 'emailAddress',
    FIRST_NAME: 'first_name',
    GENDER: 'gender',
    DOB: 'dateOfBirth',
    CONFIRM_PASSWORD: 'confirm_password',
    ENTER_PIN: 'enterPin',
    CONFIRM_PIN: 'confirmPin',
    CUREENT_PIN: 'cureentPin',
    NEW_PIN: 'newPin',
    CURRENT_PASSWORD: 'currentPassword',
    NEW_PASSWORD: 'newPassword',
  },
  KEYBOARD_TYPE: {
    DEFAULT: 'default',
    NUMBER_PAD: 'number-pad',
    DECIMAL_PAD: 'decimal-pad',
    NUMERIC: 'numeric',
    EMAIL_ADDRESS: 'email-address',
    PHONE_PAD: 'phone-pad',
    URL: 'url',
  },

  STORAGE: {
    ISLOGGED: 'ISLOGGED',
    ISONBOARDING: 'ISONBOARDING',
    TOKEN: 'token',
    USER_DATA: 'USER_DATA',
    FCM_TOKEN: 'FCM_TOKEN',
    EMAIL: 'email',
    WAITLIST: 'WAITLIST',
    SIMILAR_LIST: 'SIMILAR_LIST',
    SCREEN_NAME: 'SCREEN',
    IS_UPDATE: 'IS_UPDATE',
  },

  THEME: {
    colors: {
      APP_BACKGROUND: '#FAFAFA',
      LIGHT_GRAY: '#D4D4D8',
      BLACK: '#000000',
      QUICK_SILVER: '#A1A1AA',
      Dark_Gunmetal: '#1D2433',
      LIGHT_BLUE: 'rgba(19, 16, 78, 80)',
      SONIC_SILVER: '#71717A',
      PLATINUM_COLOR: '#E4E4E7',
      PRIMARY_COLOR: '#1D4ED8',
      CHARCOAL_COLOR: '#344054',
      PRIMARY_ONE_COLOR: '#2F92ED',
      PRIMARY_SECOND_COLOR: '#1A5D9A',
      Light_Gunmetal: 'rgba(29, 36, 51, 0.65)',
      Light_Primary_Gunmetal: 'rgba(29, 36, 51, 0.8)',
      LIGHT_WHITE: '#E1E6EF',
      CULTURED: '#F4F4F5',
      PRIMARY_COLORS: {
        100: '#F0F5FF',
      },
      TAB_COLOR: '#F7F7F5',
      TAB_BORDER: '#F3F2F1',

      NEUTRAL: {
        100: '#F8F9FC',
        200: '#F1F3F9',
        300: '#E1E6EF',
      },
      WHITE: '#FFFFFF',
      GRAY: {
        300: '#71717A',
      },
      SECONDARY_COLOR: {
        80: 'rgba(29, 36, 51, 0.8)',
      },
      Disabled_Color: 'rgba(29, 36, 51, 0.65)',

      BackgroundColor: 'rgb(247,248,251)',
      MODAL_COLOR: 'rgba(29, 36, 51, 0.4)',
      DARK_GRAY_COLOR: '#1E1E1E',
      GRAY_COLOR: '#757575',
      WHITE_COLOR: '#fff',
      TRANSPARENT: 'transparent',
      YELLOW_COLOR: '#FFD400',
      RED: '#E02D3C',
      GRAY31: '#4F4F4F',
      GRAY11: '#1C1C1C',
      ORANGE: '#E5730B',
      MODAL_LIGHT_COLOR: 'rgba(0,0,0,0.4)',
      MODAL_BG_COLOR: 'rgba(0,0,0,0.7)',
      TRANSPARENT_5: 'rgba(0,0,0,.5)',
      GREEN: '#08875D',
      CHAT_PRIMARY_COLOR: '#D9E7FC',
      CHAT_SECONDARY_COLOR: '#FFFFFF',
      LIGHT_LINE_COLOR: {
        0: 'rgba(225, 230, 239, 0)',
        100: 'rgba(225, 230, 239, 1)',
      },
      DARK_ORANGE: '#FEF4EB',
      LIGHT_BORDER: '#F4F4F5',
      TEXT_COLOR: '#18181B',
      BLACK_OPACITY: 'rgba(0, 0, 0, 0.56)',
      LABEL_COLOURS: {
        1: '#F1F5F9',
        2: '#CBD5E1',
        3: '#1E293B',
        4: '#52525B',
        5: '#737373',
      },
      ALICE_BLUE: '#EFF6FF',
      DARK_GRAY: '#3F3F46',
    },
    typography: {
      fontWeights: {
        hairline: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
    },
    size: {
      WIDTH: Dimensions.get('window').width,
      HEIGHT: Dimensions.get('window').height,
      s2: fontResize(2),
      s3: fontResize(3),
      s4: fontResize(4),
      s6: fontResize(6),
      s8: fontResize(8),
      s10: fontResize(10),
      s12: fontResize(12),
      s14: fontResize(14),
      s16: fontResize(16),
      s18: fontResize(18),
      s20: fontResize(20),
      s21: fontResize(21),
      s22: fontResize(22),
      s24: fontResize(24),
      s26: fontResize(26),
      s28: fontResize(28),
      s30: fontResize(30),
      s32: fontResize(32),
      s34: fontResize(34),
      s36: fontResize(36),
      s38: fontResize(38),
      s40: fontResize(40),
      s42: fontResize(42),
      s44: fontResize(44),
      s46: fontResize(46),
      s48: fontResize(48),
      s50: fontResize(50),
      s60: fontResize(60),
      s70: fontResize(70),
      BUTTON_HEIGHT: fontResize(48),
      BUTTON_RADIUS: fontResize(8),
    },
  },
};
export default CONSTANTS;
